# Generated by Django 5.2.5 on 2025-08-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper_code', models.IntegerField()),
                ('revesion', models.CharField(max_length=10)),
                ('subject_code', models.IntegerField()),
                ('exam_name', models.CharField(max_length=500)),
                ('subject_name', models.CharField(max_length=500)),
                ('time', models.FloatField()),
                ('maximum_mark', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartAQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField()),
                ('level', models.CharField(choices=[('U', 'Understanding'), ('R', 'Remembering'), ('A', 'Application')], max_length=1)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('part_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_paper.parta')),
            ],
        ),
        migrations.AddField(
            model_name='parta',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_paper_details', to='question_paper.questionpaper'),
        ),
    ]
