# Generated by Django 5.2.5 on 2025-08-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0002_alter_parta_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parta',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part_a_details', to='question_paper.questionpaper'),
        ),
    ]
