# Generated by Django 5.2.5 on 2025-08-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0003_alter_parta_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part_b_details', to='question_paper.questionpaper')),
            ],
        ),
        migrations.CreateModel(
            name='PartBQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_questions', models.IntegerField()),
                ('each_questions_mark', models.FloatField()),
                ('module', models.IntegerField()),
                ('level', models.CharField(choices=[('U', 'Understanding'), ('R', 'Remembering'), ('A', 'Application')], max_length=1)),
                ('question', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_equation', models.TextField(blank=True, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('part_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_paper.partb')),
            ],
        ),
    ]
