# Generated by Django 5.2.5 on 2025-08-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0004_partb_partbquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partbquestions',
            name='part_b',
        ),
        migrations.DeleteModel(
            name='PartB',
        ),
        migrations.DeleteModel(
            name='PartBQuestions',
        ),
    ]
