# Generated by Django 5.2.5 on 2025-08-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0006_partb_partbquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='partb',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
