# Generated by Django 5.2.5 on 2025-09-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0007_partb_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partb',
            name='each_questions_mark',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='PartC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('required_questions', models.IntegerField()),
                ('each_questions_mark', models.IntegerField()),
                ('total', models.IntegerField()),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part_c_details', to='question_paper.questionpaper')),
            ],
        ),
        migrations.CreateModel(
            name='PartCQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField()),
                ('level', models.CharField(choices=[('U', 'Understanding'), ('R', 'Remembering'), ('A', 'Application')], max_length=1)),
                ('question', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_equation', models.TextField(blank=True, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('part_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_paper.partc')),
            ],
        ),
    ]
