# Generated by Django 5.2.5 on 2025-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0008_alter_partb_each_questions_mark_partc_partcquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='partc',
            name='or_question',
            field=models.BooleanField(default=False),
        ),
    ]
