# Generated by Django 5.2.5 on 2025-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0009_partc_or_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcquestions',
            name='is_or_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partcquestions',
            name='or_group_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
