# Generated by Django 5.2.5 on 2025-12-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0010_partcquestions_is_or_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partaquestions',
            name='module_outcome',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partbquestions',
            name='module_outcome',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partcquestions',
            name='module_outcome',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='module1_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='module2_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='module3_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='module4_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='percent_A',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='percent_R',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='percent_U',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='time',
            field=models.IntegerField(help_text='Exam duration in hours'),
        ),
    ]
