# Generated by Django 5.2.5 on 2025-12-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0011_partaquestions_module_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parta',
            name='each_question_mark',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parta',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
