# Generated by Django 5.2.5 on 2025-12-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0013_partaquestions_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partaquestions',
            name='question_image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], default='bottom', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partbquestions',
            name='question_image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], default='bottom', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partcquestions',
            name='question_image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], default='bottom', max_length=10, null=True),
        ),
    ]
