# Generated by Django 6.0 on 2025-12-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0014_partaquestions_question_image_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partaquestions',
            options={'ordering': ['id', 'sub_question_letter']},
        ),
        migrations.AlterModelOptions(
            name='partbquestions',
            options={'ordering': ['id', 'sub_question_letter']},
        ),
        migrations.AlterModelOptions(
            name='partcquestions',
            options={'ordering': ['or_group_number', 'id', 'sub_question_letter']},
        ),
        migrations.AddField(
            model_name='partaquestions',
            name='is_sub_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partaquestions',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='question_paper.partaquestions'),
        ),
        migrations.AddField(
            model_name='partaquestions',
            name='question_image_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (200px)'), ('medium', 'Medium (400px)'), ('large', 'Large (600px)'), ('xlarge', 'Extra Large (800px)')], default='medium', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partaquestions',
            name='sub_question_letter',
            field=models.CharField(blank=True, help_text='For sub-questions: a, b, c, etc.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='partbquestions',
            name='is_sub_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partbquestions',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='question_paper.partbquestions'),
        ),
        migrations.AddField(
            model_name='partbquestions',
            name='question_image_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (200px)'), ('medium', 'Medium (400px)'), ('large', 'Large (600px)'), ('xlarge', 'Extra Large (800px)')], default='medium', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partbquestions',
            name='sub_question_letter',
            field=models.CharField(blank=True, help_text='For sub-questions: a, b, c, etc.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='partcquestions',
            name='is_sub_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partcquestions',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='question_paper.partcquestions'),
        ),
        migrations.AddField(
            model_name='partcquestions',
            name='question_image_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (200px)'), ('medium', 'Medium (400px)'), ('large', 'Large (600px)'), ('xlarge', 'Extra Large (800px)')], default='medium', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partcquestions',
            name='sub_question_letter',
            field=models.CharField(blank=True, help_text='For sub-questions: a, b, c, etc.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='partaquestions',
            name='question_image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top - Text above image'), ('middle', 'Middle - Text split (first line above, second below)'), ('bottom', 'Bottom - Text below image'), ('split', 'Split - First line above, image centered, second line below')], default='bottom', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partbquestions',
            name='question_image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top - Text above image'), ('middle', 'Middle - Text split (first line above, second below)'), ('bottom', 'Bottom - Text below image'), ('split', 'Split - First line above, image centered, second line below')], default='bottom', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partcquestions',
            name='question_image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top - Text above image'), ('middle', 'Middle - Text split (first line above, second below)'), ('bottom', 'Bottom - Text below image'), ('split', 'Split - First line above, image centered, second line below')], default='bottom', max_length=10, null=True),
        ),
    ]
