# Generated by Django 6.0 on 2026-01-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0015_alter_partaquestions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partaquestions',
            options={'ordering': ['id', 'sub_question_letter'], 'verbose_name': 'Part A Question', 'verbose_name_plural': 'Part A Questions'},
        ),
        migrations.AlterModelOptions(
            name='partbquestions',
            options={'ordering': ['id', 'sub_question_letter'], 'verbose_name': 'Part B Question', 'verbose_name_plural': 'Part B Questions'},
        ),
        migrations.AlterModelOptions(
            name='partcquestions',
            options={'ordering': ['or_group_number', 'id', 'sub_question_letter'], 'verbose_name': 'Part C Question', 'verbose_name_plural': 'Part C Questions'},
        ),
        migrations.AddField(
            model_name='partaquestions',
            name='text_below_image',
            field=models.TextField(blank=True, help_text='Text that will appear below the image (only for middle position)', null=True, verbose_name='Text Below Image'),
        ),
        migrations.AddField(
            model_name='partbquestions',
            name='text_below_image',
            field=models.TextField(blank=True, help_text='Text that will appear below the image (only for middle position)', null=True, verbose_name='Text Below Image'),
        ),
        migrations.AddField(
            model_name='partcquestions',
            name='text_below_image',
            field=models.TextField(blank=True, help_text='Text that will appear below the image (only for middle position)', null=True, verbose_name='Text Below Image'),
        ),
        migrations.AlterField(
            model_name='partaquestions',
            name='question_image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top - Text above image'), ('middle', 'Middle - Text above and below image'), ('bottom', 'Bottom - Text below image')], default='top', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partbquestions',
            name='question_image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top - Text above image'), ('middle', 'Middle - Text above and below image'), ('bottom', 'Bottom - Text below image')], default='top', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partcquestions',
            name='question_image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top - Text above image'), ('middle', 'Middle - Text above and below image'), ('bottom', 'Bottom - Text below image')], default='top', max_length=10, null=True),
        ),
    ]
