# Generated by Django 5.2.5 on 2026-01-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0016_alter_partaquestions_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exam name', max_length=500, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this exam name in dropdown')),
                ('display_order', models.IntegerField(default=0, help_text='Order in dropdown (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Exam Name',
                'verbose_name_plural': 'Exam Names',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Revision year (e.g., 2015, 2021)', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this revision in dropdown')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Subject code', max_length=20, unique=True)),
                ('subject_name', models.CharField(help_text='Full subject name', max_length=500)),
                ('duration_hours', models.IntegerField(default=3, help_text='Exam duration in hours')),
                ('is_active', models.BooleanField(default=True, help_text='Show this subject in dropdown')),
            ],
            options={
                'verbose_name': 'Subject Code',
                'verbose_name_plural': 'Subject Codes',
                'ordering': ['code'],
            },
        ),
    ]
