# Generated by Django 5.2.5 on 2026-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0017_examname_revision_subjectcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_code', models.CharField(help_text='Module Outcome Code (e.g. M1.01)', max_length=20, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description of the outcome', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Module Outcome',
                'verbose_name_plural': 'Module Outcomes',
                'ordering': ['outcome_code'],
            },
        ),
        migrations.CreateModel(
            name='QuestionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.IntegerField(help_text='Module Number', unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['module_number'],
            },
        ),
        migrations.AddField(
            model_name='partaquestions',
            name='answer_equation',
            field=models.TextField(blank=True, help_text='LaTeX equation for answer', null=True),
        ),
        migrations.AddField(
            model_name='partaquestions',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
    ]
