# Generated by Django 5.2.5 on 2026-01-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0018_moduleoutcome_questionmodule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Instruction text')),
                ('part_type', models.CharField(choices=[('A', 'Part A'), ('B', 'Part B'), ('C', 'Part C')], default='A', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Section Instruction',
                'verbose_name_plural': 'Section Instructions',
            },
        ),
    ]
