# Generated by Django 5.2.5 on 2026-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0019_sectioninstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_max_marks', models.IntegerField(default=75, help_text='Default Maximum Marks for new Question Papers')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='exam_marks',
            field=models.IntegerField(default=75, help_text='Maximum Marks to be printed on the paper'),
        ),
    ]
