# Generated by Django 5.2.5 on 2026-01-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_paper', '0020_systemconfiguration_questionpaper_exam_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
    ]
